# Generated by Django 4.1.2 on 2022-10-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_allusers_city_remove_allusers_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='category',
            field=models.CharField(default='patient', max_length=50),
        ),
        migrations.AddField(
            model_name='allusers',
            name='password1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
