# Generated by Django 4.1.2 on 2022-10-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_allusers_category_allusers_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='birthdate',
        ),
    ]
