# Generated by Django 4.1.2 on 2022-11-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assessmenttest_allusers_specialist_id'),
        ('users', '0007_remove_allusers_birthdate'),
    ]

    operations = [
    ]
