# Generated by Django 4.1.2 on 2022-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assessmenttest_allusers_specialist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='category',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('doctor', 'Doctor')], default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_1',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_2',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_3',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_4',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_5',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_6',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_7',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_8',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_9',
            field=models.CharField(choices=[('1', 'Not at all'), ('2', 'Several Days'), ('3', 'More than half the Days'), ('4', 'Nearly everyday')], max_length=200),
        ),
    ]
