# Generated by Django 4.1.2 on 2022-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_allusers_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_1',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_2',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_3',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_4',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_5',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_6',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_7',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_8',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='answer_9',
            field=models.CharField(choices=[('Not at all', '1'), ('Several Days', '2'), ('More than half the Days', '3'), ('Nearly everydays', '4')], max_length=200),
        ),
    ]
