# Generated by Django 4.1.2 on 2022-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20221103_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='category',
            field=models.CharField(choices=[('patient', 'Patient'), ('counselor', 'Counselor'), ('doctor', 'Doctor')], default='patient', max_length=50),
        ),
    ]
