# Generated by Django 4.1.2 on 2022-11-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_assessmenttest_answer_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_6',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_7',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_8',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='answer_9',
        ),
    ]
