# Generated by Django 4.1.2 on 2022-11-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_allusers_birthdate_alter_allusers_category'),
        ('users', '0011_remove_assessmenttest_answer_1_and_more'),
    ]

    operations = [
    ]
