# Generated by Django 4.1.2 on 2022-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20221108_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_1',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_2',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_3',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_4',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_5',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_6',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_7',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_8',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='answer_9',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Several Days', 'Several Days'), ('More than half the Days', 'More than half the Days'), ('Nearly everydays', 'Nearly everydays')], default='Not at all', max_length=200),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='category',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('doctor', 'Doctor')], default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
