# Generated by Django 4.1.2 on 2022-11-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_assessmenttest_answer_1_assessmenttest_answer_2_and_more'),
        ('users', '0014_user_delete_allusers_and_more'),
    ]

    operations = [
    ]
