# Generated by Django 4.1.2 on 2022-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20221116_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttest',
            name='assign_specialist_id',
        ),
        migrations.RemoveField(
            model_name='assessmenttest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='appointmentYear',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2022', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialist_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
