# Generated by Django 4.1.2 on 2022-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_assessmenttest_appointmentam_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialist_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
