# Generated by Django 4.1.2 on 2022-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_specialist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentAm_Pm',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentDay',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentHour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentMin',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentMonth',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='appointmentYear',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
