# Generated by Django 4.1.2 on 2022-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_assessmenttest_appointmentam_pm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmenttest',
            old_name='appointmentAm_Pm',
            new_name='appointmentAmPm',
        ),
    ]
